######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 14 02:24:11 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += contact.h contactfactory.h contactlist.h
SOURCES += contact.cpp contactfactory.cpp contactlist.cpp main.cpp
